# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-29 01:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('ra', models.IntegerField(unique=True, verbose_name='RA')),
                ('password', models.CharField(max_length=200, verbose_name='Senha')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('email', models.EmailField(max_length=50, verbose_name='E-Mail')),
                ('perfil', models.CharField(default='A', max_length=1, verbose_name='Perfil')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Arquivosquestao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.CharField(db_column='Arquivo', max_length=500)),
            ],
            options={
                'db_table': 'ArquivosQuestao',
            },
        ),
        migrations.CreateModel(
            name='Arquivosresposta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.CharField(db_column='Arquivo', max_length=500)),
            ],
            options={
                'db_table': 'ArquivosResposta',
            },
        ),
        migrations.CreateModel(
            name='Avisos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Titulo')),
                ('texto', models.TextField(verbose_name='Texto')),
            ],
        ),
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assunto', models.CharField(max_length=50, verbose_name='Assunto')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome')),
                ('mensagem', models.TextField(verbose_name='Mensagem')),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sigla', models.CharField(db_column='Sigla', max_length=5, unique=True)),
                ('nome', models.CharField(db_column='Nome', max_length=50, unique=True)),
            ],
            options={
                'db_table': 'Curso',
            },
        ),
        migrations.CreateModel(
            name='Cursoturma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_curso', models.ForeignKey(db_column='ID_Curso', on_delete=django.db.models.deletion.DO_NOTHING, to='core.Curso')),
            ],
            options={
                'db_table': 'CursoTurma',
            },
        ),
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(db_column='Nome', max_length=240, unique=True)),
                ('cargahoraria', models.SmallIntegerField(db_column='CargaHoraria')),
                ('teoria', models.DecimalField(db_column='Teoria', decimal_places=0, max_digits=3)),
                ('pratica', models.DecimalField(db_column='Pratica', decimal_places=0, max_digits=3)),
                ('ementa', models.TextField(db_column='Ementa')),
                ('competencias', models.TextField(db_column='Competencias')),
                ('habilidades', models.TextField(db_column='Habilidades')),
                ('conteudo', models.TextField(db_column='Conteudo')),
                ('bibliografia_basica', models.TextField(db_column='Bibliografia_Basica')),
                ('biliografia_complementar', models.TextField(db_column='Biliografia_Complementar')),
            ],
            options={
                'db_table': 'Disciplina',
            },
        ),
        migrations.CreateModel(
            name='Disciplinaofertada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.SmallIntegerField(db_column='Ano')),
                ('semestre', models.CharField(db_column='Semestre', max_length=1)),
                ('id_disciplina', models.ForeignKey(db_column='ID_Disciplina', on_delete=django.db.models.deletion.DO_NOTHING, to='core.Disciplina')),
            ],
            options={
                'db_table': 'DisciplinaOfertada',
            },
        ),
        migrations.CreateModel(
            name='Gradecurricular',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.SmallIntegerField(db_column='Ano')),
                ('semestre', models.CharField(db_column='Semestre', max_length=1)),
                ('id_curso', models.ForeignKey(db_column='ID_Curso', on_delete=django.db.models.deletion.DO_NOTHING, to='core.Curso')),
            ],
            options={
                'db_table': 'GradeCurricular',
            },
        ),
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'Matricula',
            },
        ),
        migrations.CreateModel(
            name='MensagemAluno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assunto', models.CharField(max_length=100, verbose_name='Assunto')),
                ('mensagem', models.TextField(verbose_name='Mensagem')),
            ],
        ),
        migrations.CreateModel(
            name='Periodo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.SmallIntegerField(db_column='Numero')),
                ('id_gradecurricular', models.ForeignKey(db_column='ID_GradeCurricular', on_delete=django.db.models.deletion.DO_NOTHING, to='core.Gradecurricular')),
            ],
            options={
                'db_table': 'Periodo',
            },
        ),
        migrations.CreateModel(
            name='Periododisciplina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_disciplina', models.ForeignKey(db_column='ID_Disciplina', on_delete=django.db.models.deletion.DO_NOTHING, to='core.Disciplina')),
                ('id_periodo', models.ForeignKey(db_column='ID_Periodo', on_delete=django.db.models.deletion.DO_NOTHING, to='core.Periodo')),
            ],
            options={
                'db_table': 'PeriodoDisciplina',
            },
        ),
        migrations.CreateModel(
            name='Questao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(db_column='Numero')),
                ('data_limite_entrega', models.DateField(db_column='Data_Limite_Entrega', max_length=10)),
                ('descricao', models.TextField(db_column='Descricao')),
                ('data', models.DateTimeField(db_column='Data', max_length=10)),
            ],
            options={
                'db_table': 'Questao',
            },
        ),
        migrations.CreateModel(
            name='Resposta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_avaliacao', models.DateTimeField(db_column='Data_Avaliacao', max_length=10)),
                ('nota', models.DecimalField(db_column='Nota', decimal_places=2, max_digits=4, null=True)),
                ('avaliacao', models.TextField(db_column='Avaliacao', null=True)),
                ('descricao', models.TextField(db_column='Descricao')),
                ('data_de_envio', models.DateTimeField(db_column='Data_de_Envio', max_length=10)),
                ('id_questao', models.ForeignKey(db_column='ID_Questao', on_delete=django.db.models.deletion.DO_NOTHING, to='core.Questao')),
            ],
            options={
                'db_table': 'Resposta',
            },
        ),
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turma', models.CharField(db_column='Identificacao_Turma', max_length=5)),
                ('turno', models.CharField(db_column='Turno', max_length=15)),
                ('id_disciplinaofertada', models.ForeignKey(db_column='ID_DisciplinaOfertada', on_delete=django.db.models.deletion.DO_NOTHING, to='core.Disciplinaofertada')),
            ],
            options={
                'db_table': 'Turma',
            },
        ),
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('usuario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('celular', models.CharField(db_column='Celular', max_length=11)),
                ('sigla_curso', models.CharField(db_column='Sigla_Curso', max_length=2)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Curso')),
            ],
            options={
                'db_table': 'Aluno',
            },
            bases=('core.usuario',),
        ),
        migrations.CreateModel(
            name='Coordenador',
            fields=[
                ('usuario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('apelido', models.CharField(max_length=30, unique=True, verbose_name='Apelido')),
            ],
            options={
                'abstract': False,
            },
            bases=('core.usuario',),
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('usuario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('apelido', models.CharField(db_column='Apelido', max_length=30, unique=True)),
                ('celular', models.CharField(db_column='Celular', max_length=11)),
            ],
            options={
                'db_table': 'Professor',
            },
            bases=('core.usuario',),
        ),
        migrations.AddField(
            model_name='questao',
            name='id_turma_questao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Turma'),
        ),
        migrations.AddField(
            model_name='matricula',
            name='id_turma_matricula',
            field=models.ForeignKey(db_column='ID_Turma', on_delete=django.db.models.deletion.DO_NOTHING, to='core.Turma'),
        ),
        migrations.AddField(
            model_name='cursoturma',
            name='id_turma_cursoturma',
            field=models.ForeignKey(db_column='ID_Turma', on_delete=django.db.models.deletion.DO_NOTHING, to='core.Turma'),
        ),
        migrations.AddField(
            model_name='avisos',
            name='turma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Turma'),
        ),
        migrations.AddField(
            model_name='arquivosresposta',
            name='id_resposta',
            field=models.ForeignKey(db_column='ID_Resposta', on_delete=django.db.models.deletion.DO_NOTHING, to='core.Resposta'),
        ),
        migrations.AddField(
            model_name='arquivosquestao',
            name='id_questao',
            field=models.ForeignKey(db_column='ID_Questao', on_delete=django.db.models.deletion.DO_NOTHING, to='core.Questao'),
        ),
        migrations.AddField(
            model_name='turma',
            name='id_professor',
            field=models.ForeignKey(db_column='ID_Professor', on_delete=django.db.models.deletion.DO_NOTHING, to='core.Professor'),
        ),
        migrations.AddField(
            model_name='resposta',
            name='id_aluno',
            field=models.ForeignKey(db_column='ID_Aluno', on_delete=django.db.models.deletion.DO_NOTHING, to='core.Aluno'),
        ),
        migrations.AlterUniqueTogether(
            name='questao',
            unique_together=set([('id_turma_questao', 'numero')]),
        ),
        migrations.AlterUniqueTogether(
            name='periododisciplina',
            unique_together=set([('id_periodo', 'id_disciplina')]),
        ),
        migrations.AlterUniqueTogether(
            name='periodo',
            unique_together=set([('id_gradecurricular', 'numero')]),
        ),
        migrations.AddField(
            model_name='mensagemaluno',
            name='aluno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Aluno'),
        ),
        migrations.AddField(
            model_name='mensagemaluno',
            name='professor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Professor'),
        ),
        migrations.AddField(
            model_name='matricula',
            name='id_aluno',
            field=models.ForeignKey(db_column='ID_Aluno', on_delete=django.db.models.deletion.DO_NOTHING, to='core.Aluno'),
        ),
        migrations.AlterUniqueTogether(
            name='gradecurricular',
            unique_together=set([('id_curso', 'ano', 'semestre')]),
        ),
        migrations.AlterUniqueTogether(
            name='disciplinaofertada',
            unique_together=set([('id_disciplina', 'ano', 'semestre')]),
        ),
        migrations.AlterUniqueTogether(
            name='cursoturma',
            unique_together=set([('id_curso', 'id_turma_cursoturma')]),
        ),
        migrations.AddField(
            model_name='avisos',
            name='professor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Professor'),
        ),
        migrations.AlterUniqueTogether(
            name='arquivosresposta',
            unique_together=set([('id_resposta', 'arquivo')]),
        ),
        migrations.AlterUniqueTogether(
            name='arquivosquestao',
            unique_together=set([('id_questao', 'arquivo')]),
        ),
        migrations.AlterUniqueTogether(
            name='turma',
            unique_together=set([('id_disciplinaofertada', 'id_professor')]),
        ),
        migrations.AlterUniqueTogether(
            name='resposta',
            unique_together=set([('id_questao', 'id_aluno')]),
        ),
        migrations.AlterUniqueTogether(
            name='matricula',
            unique_together=set([('id_aluno', 'id_turma_matricula')]),
        ),
    ]
