# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-29 02:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='questao',
            name='id_professor_questao',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='core.Professor'),
            preserve_default=False,
        ),
    ]
