# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-29 09:02
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_questao_id_professor_questao'),
    ]

    operations = [
        migrations.AddField(
            model_name='turma',
            name='max_alunos',
            field=models.IntegerField(default='40', validators=[django.core.validators.MaxValueValidator(40), django.core.validators.MinValueValidator(1)], verbose_name='Maximo_Alunos'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='questao',
            name='data',
            field=models.DateTimeField(auto_now_add=True, db_column='Data', max_length=10),
        ),
        migrations.AlterField(
            model_name='questao',
            name='data_limite_entrega',
            field=models.DateField(db_column='Data_Limite_Entrega', help_text='DD/MM/AAAA', max_length=10),
        ),
    ]
